### ISSUE TITLE
suggestion for examples in README.md

### ISSUE THREAD

**Issue by vd1** [tech-srl/RASP#13]
Regarding "Check if a letter is in your input at all:" one could also use the code right above like so:
```
 >> aggregate(full_s,indicator(tokens == "e")) > 0; 
         s-op: out
         Example: out("hey") = [T]*3 (bools)
```

**Comment by gailweiss** [comment]
indeed, there are always alternate solutions! the example is there to show you that there is an `in` operator which makes life easier and neater
